
package WSKMassages;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MassagesService", targetNamespace = "http://WS/", wsdlLocation = "http://192.168.1.247:20162/Massages?wsdl")
public class MassagesService
    extends Service
{

    private final static URL MASSAGESSERVICE_WSDL_LOCATION;
    private final static WebServiceException MASSAGESSERVICE_EXCEPTION;
    private final static QName MASSAGESSERVICE_QNAME = new QName("http://WS/", "MassagesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.247:20162/Massages?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASSAGESSERVICE_WSDL_LOCATION = url;
        MASSAGESSERVICE_EXCEPTION = e;
    }

    public MassagesService() {
        super(__getWsdlLocation(), MASSAGESSERVICE_QNAME);
    }

    public MassagesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MASSAGESSERVICE_QNAME, features);
    }

    public MassagesService(URL wsdlLocation) {
        super(wsdlLocation, MASSAGESSERVICE_QNAME);
    }

    public MassagesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MASSAGESSERVICE_QNAME, features);
    }

    public MassagesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MassagesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Massages
     */
    @WebEndpoint(name = "MassagesPort")
    public Massages getMassagesPort() {
        return super.getPort(new QName("http://WS/", "MassagesPort"), Massages.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Massages
     */
    @WebEndpoint(name = "MassagesPort")
    public Massages getMassagesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WS/", "MassagesPort"), Massages.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASSAGESSERVICE_EXCEPTION!= null) {
            throw MASSAGESSERVICE_EXCEPTION;
        }
        return MASSAGESSERVICE_WSDL_LOCATION;
    }

}
